### ISSUE TITLE
Update the documentation once contributions are accepted

### ISSUE THREAD

**Issue by rouazana** [linagora/gatling-imap#15]
For the moment we use a fork of jmapnio.
Once these contributions are accepted we will be able to use main project:
https://github.com/lafaspot/imapnio/pull/28
https://github.com/lafaspot/imapnio/pull/29

**Comment by rouazana** [comment]
Contributions merged, just waiting for the new imapnio version to be available on maven central.

**Comment by chibenwa** [comment]
Contribution have been merged upstream.

https://github.com/linagora/gatling-imap/pull/16 solved this.
