### ISSUE TITLE
Migrate Yahoo resolver from bintray

### ISSUE THREAD

**Issue by renaudboyer** [linagora/gatling-imap#52]
Yahoo resolver links to bintray to fetch com.yahoo.imapnio.

As Bintray have been shut down and dependency fetching fail.

Resolvers link is [here](https://github.com/linagora/gatling-imap/blob/master/build.sbt#L32)

**Comment by Arsnael** [comment]
Good catch, thanks for notifying us @renaudboyer :)

**Comment by renaudboyer** [comment]
I'm pushing soon a PR, it seems to compile with default resolver

**Comment by Arsnael** [comment]
As discussed, the version used for now here, 0.3.15, is only hosted on bintray that has been shut down. I don't see any other hosting for that version.

However it would be good to try an upgrade of that lib :) That's probably the reasonable way to go. 

Will try something tomorrow!

**Comment by Arsnael** [comment]
Yes there was, that's why we had to revert back unfortunately a while ago^^'

Yet an other netty issue :D

**Comment by Arsnael** [comment]
https://github.com/linagora/gatling-imap/pull/54
