### ISSUE TITLE
Gatling IMAP is starting a thread per user, caausing OOM

### ISSUE THREAD

**Issue by chibenwa** [linagora/gatling-imap#56]
## Symptomes

Starting ~3400 users will cause gatling IMAP to throw an OOM, whatever the rate of requests

## Root cause

I decided to do a flame graph analysis of gatling IMAP and found that we were spending 73% of our time starting new threads:

![Screenshot from 2022-03-29 10-13-23](https://user-images.githubusercontent.com/6928740/160525818-16b68539-c70c-4d9e-a0aa-3001bfc98034.png)

Reviewing the applicative stack, found the Akka actor spinning threads like crazy: this is upon connecting new clients:

![Screenshot from 2022-03-29 10-14-56](https://user-images.githubusercontent.com/6928740/160525963-da23df5a-767c-485a-9ec4-7c88b152f91d.png)

Looking at the code, we do create a new IMAP async client backed by its own Netty EventLoopGroup on every connected users. 

Why the OOM? Simple: each thread stack reserves 1M of memory and 3000+ of them would consume 3GB of memory and we could quickly hit limits.

## The fix

Those are expensive resources and needs to be shared.

**Comment by Arsnael** [comment]
Merged
